name: Basic CI for LMS

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  check-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Backend
      - name: Install backend dependencies
        run: |
          cd lms-backend
          npm install

      - name: Start backend server
        run: |
          cd lms-backend
          npm start &
          sleep 10
          curl --fail http://localhost:5001/api/health || exit 1

      # Frontend
      - name: Install frontend dependencies
        run: |
          cd lms-frontend
          npm install

      - name: Build frontend
        run: |
          cd lms-frontend
          npm run build

      - name: Start frontend server
        run: |
          cd lms-frontend
          npm start &
          sleep 10
          curl --fail http://localhost:3000 || exit 1
