name: Basic CI for LMS

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

jobs:
  check-services:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install backend dependencies
        run: |
          cd lms-backend
          npm install

      - name: Start backend server
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_USERNAME: ${{ secrets.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: |
          cd lms-backend
          npm start &
          sleep 10
          curl --fail http://localhost:5001/api/health || exit 1

      - name: Install frontend dependencies
        run: |
          cd lms-frontend
          npm install

      - name: Build frontend
        run: |
          cd lms-frontend
          npm run build

      - name: Start frontend server
        run: |
          cd lms-frontend
          npm start &
          sleep 10
          curl --fail http://localhost:3000 || exit 1
